version: '3'

services:
  portal:
    build:
      context: ./portal
    networks:
      - microportal

  dashboard:
    build:
      context: ./dashboard
    networks:
      - microportal

  settings:
    build:
      context: ./settings
    networks:
      - microportal

  root:
    build:
      context: ./root
    networks:
      - microportal

  proxy:
    image: nginx:stable-alpine
    depends_on:
      - portal
      - dashboard
      - settings
      - root
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - microportal

networks:
  microportal:
